version: "3"

x-kafka_base: &kafka_base
  image: "bitnami/kafka:latest"
  # environment: 
    # - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    # - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  networks:
    - kafka-system

services:
  kafka01:
    <<: *kafka_base
    container_name: kafka01
    ports:
      - "9093:9093"
    # volumes:
    #   - kafka-data:/bitnami/kafka
    # entrypoint: ./wait-for-it.sh zookeeper:2181 --timeout=15
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka01:9092,EXTERNAL://localhost:9093
  kafka02:
    <<: *kafka_base
    container_name: kafka02
    ports:
      - "9094:9094"
    # volumes:
    #   - kafka-data:/bitnami/kafka
    # entrypoint: ./wait-for-it.sh zookeeper:2181 --timeout=15
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka02:9092,EXTERNAL://localhost:9094
  # kafka03:
  #   <<: *kafka_base
  #   container_name: kafka03
  #   # volumes:
  #   #   - kafka-data:/bitnami/kafka
  #   # entrypoint: ./wait-for-it.sh zookeeper:2181 --timeout=15
  #   environment: 
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #     - KAFKA_BROKER_ID=3
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka03:9092,EXTERNAL://localhost:9093
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-system
    # entrypoint: bin/zookeeper-server-start.sh config/zookeeper.properties

  mysql:
    image: "mysql:5"
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    networks:
      - kafka-system
networks:
  kafka-system:

volumes:
  mysql-data:
  kafka-data:
  # kafka-client-data: