version: "3.4"

# 이미지와 네트워크 정보에 대한 base service를 지정
x-datanode_base: &datanode_base
  build: ./datanode
  networks:
    - bridge

services:
  namenode:
    build: ./namenode
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/root/hadoop/dfs/name
      - /tmp:/tmp
    networks:
      - bridge
  
  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/root/hadoop/dfs/data
  
  datanode02:
    <<: *datanode_base
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/root/hadoop/dfs/data

  datanode03:
    <<: *datanode_base
    container_name: datanode03
    hostname: datanode03
    volumes:
      - datanode03:/root/hadoop/dfs/data

  datanode04:
    <<: *datanode_base
    container_name: datanode04
    hostname: datanode04
    volumes:
      - datanode04:/root/hadoop/dfs/data
volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:
  datanode04:

networks:
  bridge: